# Generated by Django 6.0.4 on 2026-05-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_profile_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='pfp/profile_pics'),
        ),
    ]
