# Generated by Django 6.0.4 on 2026-06-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pfp/default.png', upload_to='pfp/profile_pics'),
        ),
    ]
