# Generated by Django 6.0.4 on 2026-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuário', models.CharField(max_length=50, unique=True)),
                ('conteudo', models.TextField(max_length=255)),
                ('recomendado', models.BooleanField()),
            ],
        ),
    ]
