# Generated by Django 6.0.4 on 2026-04-29 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_nome_media_categoria_media_titulo'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='nomeUsuário',
        ),
        migrations.AddField(
            model_name='review',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AlterField(
            model_name='review',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='recomendado',
            field=models.BooleanField(default=True),
        ),
    ]
