# Generated by Django 6.0.4 on 2026-05-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_image_url_media_release_date_media_synopsis'),
        ('review', '0002_remove_review_nomeusuário_review_autor_review_media_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='conteudo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recomendado',
            new_name='recommended',
        ),
        migrations.RemoveField(
            model_name='review',
            name='autor',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='media.media'),
            preserve_default=False,
        ),
    ]
