# Generated by Django 6.0.4 on 2026-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_conteudo_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
