# Generated by Django 6.0.4 on 2026-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='nome',
        ),
        migrations.AddField(
            model_name='media',
            name='categoria',
            field=models.CharField(choices=[('MOVIE', 'Filme'), ('GAME', 'Videojogo'), ('BOOK', 'Livro')], default='MOVIE', max_length=10),
        ),
        migrations.AddField(
            model_name='media',
            name='titulo',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
