# Generated by Django 6.0.4 on 2026-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_nome_media_categoria_media_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='media',
            name='titulo',
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('MOVIE', 'Filme'), ('GAME', 'Videojogo'), ('BOOK', 'Livro')], default='Temporario', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(default='Temporario', max_length=255),
            preserve_default=False,
        ),
    ]
