# Generated by Django 6.0.4 on 2026-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_categoria_remove_media_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
